---
- name: Install PHP
  action: apt pkg={{item}} state=installed
  with_items:
    - php{{ php_version }}
    - libapache2-mod-php{{ php_version }}
    - php{{ php_version }}-curl
    - php{{ php_version }}-gd
    - php{{ php_version }}-json
    - php{{ php_version }}-xmlrpc
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-dom
    - php{{ php_version }}-exif
    - php{{ php_version }}-simplexml
    - zip
    - unzip
    - git
    - composer
  notify: restart apache
