---
- name: Install PHP
  action: apt pkg={{item}} state=installed
  with_items:
    - php7.3
    - libapache2-mod-php7.3
    - php7.3-curl
    - php7.3-gd
    - php7.3-json
    - php7.3-xmlrpc
    - php7.3-mbstring
    - php7.3-dom
    - php7.3-exif
    - php7.3-simplexml
    - zip
    - unzip
    - git
    - composer
  notify: restart apache
